name: Update Lines of Code in Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight (UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  count-lines:
    runs-on: ubuntu-latest
    env:
      # Check official cloc documentation for supported languages and their exact names
      # Languages to show individually in README (others will be grouped under "Others")
      HIGHLIGHT_LANGS: "JavaScript,TypeScript,JSX,Vuejs Component,PHP,C#"

      # Languages to ignore completely (not shown and not counted in totals)
      IGNORE_LANGS: "JSON,HTML,CSS,SCSS,Sass,Markdown,SVG,YAML,TOML,CSV,Text,Properties"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install required dependencies: jq (JSON processor), cloc (count lines of code), and locale settings
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq cloc locales
          sudo locale-gen en_US.UTF-8

      # Fetch public repositories (excluding forks) and clone only the default branch
      - name: Fetch and Clone Repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          USERNAME="arhamkhnz"

          # Get a list of public repositories that are not forks
          REPOS=$(curl -H "Authorization: token $GH_PAT" -s "https://api.github.com/user/repos?per_page=100" | jq -r '.[] | select(.fork == false) | .full_name') || echo "Error fetching repositories"

          mkdir -p public-repos
          cd public-repos

          for REPO in $REPOS; do
            REPO_URL="https://github.com/$REPO.git"
            AUTHENTICATED_REPO=$(echo "$REPO_URL" | sed "s/https:\/\//https:\/\/$GH_PAT@/g")
            
            # Determine the default branch dynamically and clone only that branch
            DEFAULT_BRANCH=$(curl -H "Authorization: token $GH_PAT" -s "https://api.github.com/repos/$REPO" | jq -r '.default_branch')

            # echo "Cloning $REPO (default branch: $DEFAULT_BRANCH)..."
            git clone --branch "$DEFAULT_BRANCH" --single-branch "$AUTHENTICATED_REPO" "$(basename $REPO)-$DEFAULT_BRANCH" || echo "Failed to clone a repository"
          done

          # Run cloc to analyze lines of code, excluding non-source code files
          echo "Calculating lines of code..."
          mkdir -p ../output
          cloc . --json --report-file=../output/cloc-output.json --exclude-lang="${IGNORE_LANGS}"

      # Commit and push the updated cloc-output.json and README.md to the current branch
      - name: Commit and Push Output
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # --- format helper ---
          format_number() {
            printf "%'d\n" "$1"
          }

          # Ensure grouping is enabled for every printf in this step
          export LC_ALL="en_US.UTF-8"
          export LANG="en_US.UTF-8"

          # Grab total from cloc
          TOTAL_LINES=$(jq '.SUM.code // 0' output/cloc-output.json)

          OTHER_LINES=0
          FORMATTED_BREAKDOWN=""

          # Iterate over each language and its code lines
          HL=",$(echo "$HIGHLIGHT_LANGS" | tr -d ' '),"

          while read -r entry; do
            LANG=$(echo "$entry" | jq -r '.lang')
            LINES=$(echo "$entry" | jq -r '.lines')

            if [[ "$HL" == *",$LANG,"* ]]; then
              FORMATTED=$(format_number "$LINES")
              FORMATTED_BREAKDOWN+=$(printf "%-12s --> %10s lines\n" "$LANG" "$FORMATTED")$'\n'
            else
              OTHER_LINES=$((OTHER_LINES + LINES))
            fi
          done < <(
            jq -c 'to_entries
              | map(select(.key != "header" and .key != "SUM"))
              | map({lang: .key, lines: .value.code})
              | map(select(.lines > 0))
              | .[]' output/cloc-output.json
          )

          # Add Others (formatted)
          if [[ $OTHER_LINES -gt 0 ]]; then
            FORMATTED_OTHER=$(format_number "$OTHER_LINES")
            FORMATTED_BREAKDOWN+=$(printf "%-12s --> %10s lines\n" "Others" "$FORMATTED_OTHER")$'\n'
          fi

          # Format total ONCE (do not overwrite later)
          FORMATTED_TOTAL=$(format_number "$TOTAL_LINES")

          CODE_BLOCK="\`\`\`
          [ LANGUAGES BREAKDOWN ]

          $FORMATTED_BREAKDOWN
          [ TOTAL LINES OF CODE: $FORMATTED_TOTAL ]
          \`\`\`"

          # Update README.md by replacing the section between predefined comment markers
          echo "$CODE_BLOCK" > temp_block.txt
          sed -i '/<!-- LANGUAGES BREAKDOWN START -->/,/<!-- LANGUAGES BREAKDOWN END -->/{
              //!d
              /<!-- LANGUAGES BREAKDOWN START -->/r temp_block.txt
          }' README.md

          rm temp_block.txt

          git add output/cloc-output.json README.md
          git commit -m "chore: update README and cloc-output.json with latest code stats" || echo "No changes to commit"
          git push origin HEAD
